services:
  gts:
    container_name: gts
    image: "gts:latest"
    build: .
    volumes:
      - ./src:/workspace/frontend
      - /home/minjkang/.config/gcloud:/root/.config/gcloud
    restart: unless-stopped
    network_mode: host
    
    
