# Copyright 2024 Google LLC All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http:#www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: agones.dev/v1
kind: Fleet
metadata:
  name: guess-the-sketch-app
spec:
  replicas: 10
  template:
    spec:
      health:
        initialDelaySeconds: 20
        periodSeconds: 10
      ports:
        - name: default
          containerPort: 7654
          protocol: TCP
      template:
        spec:
          containers:
            - name: guess-the-sketch-app
              image: guess-the-sketch-app
              resources:
                requests:
                  memory: 256Mi
                  cpu: 80m
                limits:
                  memory: 256Mi
                  cpu: 80m
---
apiVersion: "autoscaling.agones.dev/v1"
kind: FleetAutoscaler
metadata:
  name: fleet-autoscaler-guess-the-sketch-app
spec:
  fleetName: guess-the-sketch-app
  policy:
    type: Buffer
    buffer:
      bufferSize: 5
      minReplicas: 10
      maxReplicas: 15
