# Copyright 2023 Google LLC All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http:#www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-friendschat
  namespace: genai
  labels:
    name: demo-friendschat
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 40%
      maxUnavailable: 0
  selector:
    matchLabels:
      name: demo-friendschat
  template:
    metadata:
      labels:
        name: demo-friendschat
        version: stable
      annotations:
        instrumentation.opentelemetry.io/inject-python: "genai-instrumentation"
    spec:
      restartPolicy: Always
      containers:
      - image: demo-friendschat
        name: demo-friendschat
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        env:
        - name: ENV
          value: dev
        # TODO: Update prior to deployment
        - name: GENAI_API_ENDPOINT
          value: http://genai-api.genai.svc
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: demo-friendschat
  name: demo-friendschat
  namespace: genai
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    name: demo-friendschat
  sessionAffinity: None
  type: LoadBalancer

